### ISSUE TITLE
很棒啊，都翻译完了，感谢

### ISSUE THREAD

**Issue by 1c7** [ksco/BuildYourOwnLispCn#2]
看了英文原文到第五章，就去作者 github 问下怎么翻译，
然后作者扔了我个链接说你已经翻译了。
感谢。~~
不知道为啥这么少 star

**Comment by 1c7** [comment]
开发者头条，推库，掘进，我记得好像可以推荐链接。
我之前翻译了个200行代码的 Nodejs 编译器然后去开发者头条推荐了下，
拿了50个 star。
其实重点倒不是那几个 star，
只是翻译之后希望至少有一些人知道。而且能从翻译中学到点什么就最好了。

**Comment by 1c7** [comment]
跟原作者聊了下，跟他说了你的翻译都完成了，然后他把你的 Gitbook 链接放到官网下面了
:smile:

**Comment by ksco** [comment]
哥啊，我还没翻译完，还有很大一部分都没有翻译。

**Comment by 1c7** [comment]
@ksco  = =  啊，是吗，我只看了前5章和章节以为你都弄完了。
那我参与翻译？等我看到没翻译的部分我就帮忙你翻译

**Comment by 1c7** [comment]
Gitbook 的参与翻译要怎么弄？从来没弄过

**Comment by ksco** [comment]
欢迎参与，我总是偶尔想起来就翻译一些，进度比较慢，如果有人帮忙就太好了。
不需要使用 Gitbook，反正我是没用。。。。
直接在 GitHub PR 就好了，Gitbook 那边会自动同步。
现在翻译到 S 表达式了

**Comment by 1c7** [comment]
这样，好，那我 Fork 一下，然后改完了给你发 PR

**Comment by ksco** [comment]
翻译没啥要求，不必忠于原文，表达出意思就好了。读起来不要有翻译腔。
然后格式上你可以看一下我已经翻译的。英文的大小写不要弄错了。英文和中文之间加空格。

**Comment by 1c7** [comment]
@ksco  好，明白，谢谢。我翻译完你校对一遍就好了。

**Comment by ksco** [comment]
等翻译完了我按照你说的推广一下试试看233

**Comment by 1c7** [comment]
哈哈哈好

**Comment by 1c7** [comment]
这个 Issue 我就先放着，不 Close 了，
等翻译完了再 Close，Close 了不好找，每次要多点一次按钮。

**Comment by ksco** [comment]
Make yourself comfortable 😸

**Comment by 1c7** [comment]
哈哈哈将来要是能找图灵出版社出版，你赚点零食钱就更好了

**Comment by ksco** [comment]
不行的哈，LICENSE 不允许

**Comment by 1c7** [comment]
原来这样，那也没关系。
话说你有什么学编译器的好资料推荐吗？大部头的书我看着很郁闷。
就其他类似于原作者这种风格的。。

我睡觉去了  雾霾时间22:17了，

**Comment by ksco** [comment]
哈哈，欢迎看我自己写的教程，http://www.jianshu.com/notebooks/4157501/latest

**Comment by 1c7** [comment]
:smile:
