### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by sparkecho** [ksco/BuildYourOwnLispCn#3]
第零一章 • 介绍
这本书是给谁看的
最后一段:
对此，我只能感到抱歉。程序员们可能*****无理*****、自大、傲慢、脾气暴躁，但是这些都无可指责。毕竟每天加班累的跟狗一样，自然需要一个地方发泄。但是你需要知道的是，没有人是天生就会的。每个人都曾经是初学者。都犯过跟你一样的低级错误。所以，请不要放弃这项富有创造力的工作，而是努力去改变这个世界！
是不是： 无理 -> 无礼 ?

**Comment by ksco** [comment]
已改，谢谢！
